name: ETL CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run extract.py
        run: python etl/extract.py

      - name: Run transform.py
        run: python etl/transform.py

      - name: Run load.py
        run: python etl/load.py